version: '3.3'

services:
   wordpress:
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
        WORDPRESS_DB_HOST: wordpress.ciq4syhacdms.us-east-1.rds.amazonaws.com
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
